src/mysqlMinhaSaude/mysqlMinhaSaude/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using mysqlMinhaSaude.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MinhaSaude.Models
{

    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<CaixinhaDeRemedios> mysqlcsharpems { get; set; }
    }

}

src/mysqlMinhaSaude/mysqlMinhaSaude/Models/CaixinhaDeRemedios.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mysqlMinhaSaude.Models
{
    public class CaixinhaDeRemedios
    {

        [Key]
        public int id { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório")]
        public nomeRemedio nome { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public TipoRemedio Tipo { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public int Quantidade { get; set; }
    }
    public enum TipoRemedio
    {
        Caixa,
        Cartela,
        Unidade,
    }
    public enum nomeRemedio
    {
        Paracetamol,
        Ibuprofeno,
        Novalgina,
    }
}

src/mysqlMinhaSaude/mysqlMinhaSaude/Models/ErrorViewModel.cs
using System;

namespace mysqlMinhaSaude.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/mysqlMinhaSaude/mysqlMinhaSaude/Controllers/CaixinhaDeRemediosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MinhaSaude.Models;
using mysqlMinhaSaude.Models;

namespace mysqlMinhaSaude.Controllers
{
    public class CaixinhaDeRemediosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CaixinhaDeRemediosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CaixinhaDeRemedios
        public async Task<IActionResult> Index()
        {
            return View(await _context.mysqlcsharpems.ToListAsync());
        }

        // GET: CaixinhaDeRemedios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var caixinhaDeRemedios = await _context.mysqlcsharpems
                .FirstOrDefaultAsync(m => m.id == id);
            if (caixinhaDeRemedios == null)
            {
                return NotFound();
            }

            return View(caixinhaDeRemedios);
        }

        // GET: CaixinhaDeRemedios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CaixinhaDeRemedios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nome,Tipo,Quantidade")] CaixinhaDeRemedios caixinhaDeRemedios)
        {
            if (ModelState.IsValid)
            {
                _context.Add(caixinhaDeRemedios);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(caixinhaDeRemedios);
        }

        // GET: CaixinhaDeRemedios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var caixinhaDeRemedios = await _context.mysqlcsharpems.FindAsync(id);
            if (caixinhaDeRemedios == null)
            {
                return NotFound();
            }
            return View(caixinhaDeRemedios);
        }

        // POST: CaixinhaDeRemedios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome,Tipo,Quantidade")] CaixinhaDeRemedios caixinhaDeRemedios)
        {
            if (id != caixinhaDeRemedios.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(caixinhaDeRemedios);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CaixinhaDeRemediosExists(caixinhaDeRemedios.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(caixinhaDeRemedios);
        }

        // GET: CaixinhaDeRemedios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var caixinhaDeRemedios = await _context.mysqlcsharpems
                .FirstOrDefaultAsync(m => m.id == id);
            if (caixinhaDeRemedios == null)
            {
                return NotFound();
            }

            return View(caixinhaDeRemedios);
        }

        // POST: CaixinhaDeRemedios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var caixinhaDeRemedios = await _context.mysqlcsharpems.FindAsync(id);
            _context.mysqlcsharpems.Remove(caixinhaDeRemedios);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CaixinhaDeRemediosExists(int id)
        {
            return _context.mysqlcsharpems.Any(e => e.id == id);
        }
    }
}

src/mysqlMinhaSaude/mysqlMinhaSaude/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mysqlMinhaSaude.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace mysqlMinhaSaude.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult PerfilPaciente()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/CaixinhaDeRemedios/Create.cshtml
@model mysqlMinhaSaude.Models.CaixinhaDeRemedios

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CaixinhaDeRemedios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <select asp-for="nome" class="form-control" asp-items="Html.GetEnumSelectList<nomeRemedio>()"></select>
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<TipoRemedio>()"></select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/CaixinhaDeRemedios/Delete.cshtml
@model mysqlMinhaSaude.Models.CaixinhaDeRemedios

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>

<h3>Tem certeza que deseja deletar?</h3>
<div>
    <h4>CaixinhaDeRemedios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/CaixinhaDeRemedios/Details.cshtml
@model mysqlMinhaSaude.Models.CaixinhaDeRemedios

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>CaixinhaDeRemedios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Editar</a> |
    <a asp-action="Index">Voltar</a>
</div>

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/CaixinhaDeRemedios/Edit.cshtml
@model mysqlMinhaSaude.Models.CaixinhaDeRemedios

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>CaixinhaDeRemedios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <select asp-for="nome" class="form-control" asp-items="Html.GetEnumSelectList<nomeRemedio>()"></select>
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control"  asp-items="Html.GetEnumSelectList<TipoRemedio>()"></select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/CaixinhaDeRemedios/Index.cshtml
@model IEnumerable<mysqlMinhaSaude.Models.CaixinhaDeRemedios>

@{
    ViewData["Title"] = "Index";
}

<h1>Caixinha de Remédios</h1>

<p>
    <a asp-action="Create">Criar Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantidade)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



        <div class="tela-inicial">
            <div class="d-flex justify-content-center p-3 m-3">
                <img src="~/images/logo1.png" class="img-fluid" alt="Responsive image">
            </div>
            <div class="text-primary">
                <div class="d-flex justify-content-center p-2 ">
                    <h3>Minha Saúde Para facilitar o seu dia!</h3>
                </div>
                <div class="d-flex justify-content-center p-2">
                    <p>O Minha Saúde irá facilitar o seu dia gerindo sua rotina de remédios e procura por farmácias próximas. Basta criar uma conta e usufruir do nosso sistema.</p>
                </div>
                <div class="d-flex justify-content-center p-2">
                    <p> O melhor de tudo: gratuito para você!</p>
                </div>


                <div class="row justify-content-center">

                    <div class="card bg-light mb-3 m-2" style="max-width: 12rem;">
                        <div class="card-header">Medicamentos</div>
                        <div class="card-body ">
                            <h5 class="card-title"><?php echo $numTotalMedicamentos  ?></h5>
                            <p class="card-text">Número de mericamentos cadastrados</p>
                        </div>
                    </div>
                    <div class="card bg-light mb-3 m-2" style="max-width: 12rem;">
                        <div class="card-header">Usuários</div>
                        <div class="card-body">
                            <h5 class="card-title"><?php echo $numUsuariosAtivos  ?></h5>
                            <p class="card-text">Número de usuarios ativos no sistema</p>
                        </div>
                    </div>
                    <div class="card bg-light mb-3 m-2" style="max-width: 12rem;">
                        <div class="card-header">Tratamentos</div>
                        <div class="card-body">
                            <h5 class="card-title">0</h5>
                            <p class="card-text">Número de tratamentos em andamento</p>
                        </div>
                    </div>
                </div>
            </div>

            </div>

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/Home/PerfilPaciente.cshtml
@{
    ViewData["Title"] = "Perfil Paciente";
}

<body>
    <h1 class=" d-flex justify-content-center m-3 mb-2" style="background-color: #faebd7;">Perfil Paciente</h1>
    <section>
        <div class="overflow-scroll p-2">
            <a class="btn btn-light btn-block p-4" href="#" role="button"> Visualizar Receita</a>
            <a class="btn btn-light btn-block p-4" href="#" role="button">Tratamento</a>
            <a class="btn btn-light btn-block p-4" href="bulas.php" role="button">Bulas</a>
            <a class="btn btn-light btn-block p-4" asp-area="" asp-controller="CaixinhaDeRemedios" asp-action="Index">Caixinha de Remédios</a>
            <a class="btn btn-light btn-block p-4" href="#" role="button">Procurar preços</a>
            <a class="btn btn-light btn-block p-4" href="configuracoes.php" role="button">Configurações</a>
        </div>
    </section>
</body>

src/mysqlMinhaSaude/mysqlMinhaSaude/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mysqlMinhaSaude</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-light navbar-expand-lg" style="background-color: #83ACF2;">
            <img class="img-fluid" src="~/images/logo.png" class="detailImage" width="70" />
            <div class="col ">
                <div class="" href="#">Minha Saúde</div>
                <div class="texto mt-0"> <?= date('d-m-Y') ?></div>
                <p6 class="texto" id="timestamp"></p6>
            </div>

            <strong class="p-2">


            </strong>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="d-flex justify-content-end">
                <div class="collapse navbar-collapse p-2" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only"></span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="PerfilPaciente">Paciente</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Tratamento
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="">Cadastrar</a>
                            </div>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Medicamentos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="">Cadastrar</a>
                                <a class="dropdown-item" href="">Procurar</a>
                            </div>
                        <li class="nav-item">
                            <a class="nav-link" href="">Farmácias</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="">Sair</a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MinhaSaude - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>